FROM alpine:3.19

# instalăm g++ și dependințele 
RUN apk add --no-cache g++ build-base

# creem un user simplu elev fara drepturi 
RUN adduser -D -g "" elev

# adaugam librarie pentru timp si ram
RUN apk add --no-cache time

# setam directorul de lucru in temporar
WORKDIR /sandbox

# elev acum poate sa ruleze comenzi doar in /sandbox
RUN chown -R elev:elev /sandbox

# tot ce ruleaza ruleaza ca user fara root
USER elev

